# This is a basic workflow to help you get started with Laraboot using Github Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - dev
      - next
      - feature/*

  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Build
        id: build
        uses: laraboot-io/github-actions/commander@next
        with:
          # Replace this with
          buildtask-name: mybuildtask

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Release into DockerHub
        env:
          # or consume ${{ steps.build.outputs.buildtask_name }}
          BUILDTASK_NAME: mybuildtask
          ECR_REGISTRY: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          # Use current branch as tag
          docker tag $BUILDTASK_NAME $ECR_REGISTRY/$BUILDTASK_NAME:${GITHUB_REF##*/}
          docker push $ECR_REGISTRY/$BUILDTASK_NAME:${GITHUB_REF##*/}

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.CR_PAT }}
#      - name: Release into GH Rc
#        id: ghcr-io-release
#        env:
#          TAG: dev
#          # or consume ${{ steps.build.outputs.buildtask_name }}
#          BUILDTASK_NAME: mybuildtask
#          ECR_REGISTRY: ghcr.io/${{ github.repository_owner }}
#        run: |
#          docker tag $BUILDTASK_NAME $ECR_REGISTRY/$BUILDTASK_NAME:$TAG
#          docker push $ECR_REGISTRY/$BUILDTASK_NAME:$TAG